version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          ARTIFACTS_DIR: /tmp/artifacts
    steps:
      - checkout
      - run: mkdir -p ${ARTIFACTS_DIR} 
      - run: touch ${ARTIFACTS_DIR}/XXXX
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: ./*
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
        at: ${ARTIFACTS_DIR}
      - run: ls ${ARTIFACTS_DIR}
workflows:
  version: 2
  build_and_manually_release:
    jobs:
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
