version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: mkdir -p workspace/stuff 
      - run: touch workspace/stuff/XXXX
      - persist_to_workspace:
          root: workspace
          paths:
            - stuff 
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace
workflows:
  version: 2
  build_and_manually_release:
    jobs:      
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
