##  Circle CI v 2.0 template
##  This template builds a CI pipeline 
##    build -> wait_for_approval -> publish-github-release
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt update && apt install -y ca-certificates # needed to store artifacts 
      - run: mkdir -p workspace/stuff 
      - run: echo "TEST" > workspace/stuff/MyArtifact.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - stuff 
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/stuff    
      - run:
          name: "Publish Release on Github"
          command: |
            echo "Uploading release:${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} workspace/stuff/
workflows:
  version: 2
  build_and_manually_release:
    jobs:      
      - build:
          filters: # required: publish-github-release defines a filter.tag and all its dependencies must defined a filter.tag too
            tags:
              only: /.*/      
      - publish-github-release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/  
          requires:
            - build
